spring:
  boot:
    elasticsearch:
      rest:
        uris:
        - http://localhost:9200
        username: admin
        password: admin123
        connectionTimeout: 50000
        readTimeout: 30000
        maxConnTotal: 100
        maxConnPerRoute: 200
      index:
        refresh_interval: 1s
        number_of_shards: 5
        number_of_replicas: 1
      request:
        timeout: 20000
        refreshPolicy: wait_for
        waitForActiveShards: 2
      search:
        timeout: 10000
    http:
      uris:
      - http://localhost:9200
      port: -1
      restUris: http://localhost:9200//sql
      connectTimeout: 3000
      socketTimeout: 30000
      maxConnTotal: 5000
      maxConnPerRoute: 1024
      maxConnRoute: 1024
      monitorInterval: 300
      idelTimeout: 500
  datasource:
    price:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/price?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false&useCursorFetch=true
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 300000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdel: 1
      timeBetweenEvictionRunsMills: 60000
      minEvictableIdleTimeMills: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计
      filters: stat
    cost:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/Cost?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=round&useSSL=false&useCursorFetch=true
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 300000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdel: 1
      timeBetweenEvictionRunsMills: 60000
      minEvictableIdleTimeMills: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计
      filters: stat
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /price-prod
    template:
      queue: price_es_sync_queue
      routing-key: price_es_sync_routing_key
      exchange: price_es_sync_exchange
      reply-timeout: 1000ms
    listener:
      type: direct
      direct:
        concurrency: 15
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    publisher-confirms: true
    publisher-returns: true
  elasticsearch:
    host: localhost
    port: -1
    protocol: http
    maxConnTotal: 200
    maxConnPerRoute: 300
    socketTimeout: 3000
    ioThreadCount: 10
    #host=localhost
    #host=127.0.0.1
    #port: 9200
    #protocol=https
  threadpool:
    corePoolSize: 6
    maximumPoolSize: 10
    keepAliveTime: 0
    unit: MILLISECONDS
    queueQuantity: 200000
    recycleQuantity: 20
  schema:
    tableNames:
    - cost_pcg_mtm
#    - cost_dcg_mtm
#    - cost_mbg_mtm
#    - cost_pcg_cto
#    - cost_dcg_cto
    indexes:
    - cfe_pcg_mtmsalesorg_2
#    - cfe_dcg_mtmsalesorg_test
#    - cfe_mbg_mtmsalesorg_test
#    - cfe_pcg_ctovksalesorg_test
#    - cfe_dcg_ctovksalesorg_test
    mapping: true
    updateMapping: false
    pageSize: 6
    bulkSize: 10000

logging:
  level:
    root: INFO